name: Build static binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build all binaries in container
        run: |
          IMAGE="debian:unstable"
          ARCH="${{ matrix.arch }}"

          if [ "$ARCH" = "aarch64" ]; then
            PLATFORM="linux/arm64"
          else
            PLATFORM="linux/amd64"
          fi

          docker run --rm --platform "$PLATFORM" -v "$PWD":/workspace -w /workspace -e ARCH="$ARCH" $IMAGE bash -e -c '
            set -e

            mkdir -p am-bins dist

            RED="\033[0;31m"
            TERMINAL_WIDTH="${COLUMNS:-80}"
            DIVIDING_LINE=$(printf "%*s" "$TERMINAL_WIDTH" "" | tr " " "-")

            utils="7z \
            ar \
            base64 basename bzip2 \
            cat chmod chown chroot clear column cp curl cut \
            dd diff dirname du \
            echo \
            file fold \
            gawk grep \
            head \
            id \
            kill killall \
            less ln ls \
            notify-send \
            mawk md5sum mkdir more mount mv \
            printf \
            readlink realpath rev rm \
            sed sh sha1sum sha256sum sha512sum sleep sort strace strings strip swapoff swapon \
            tail tar tee test tput top touch tr tty \
            umount uname uncompress uniq unshare unxz unzip uptime \
            watch wc wget \
            xargs xz xzcat \
            yes \
            zcat zsync"

            # Download quick-sharun if missing
            if ! command -v quick-sharun >/dev/null 2>&1; then
              curl -#Lo quick-sharun https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/refs/heads/main/useful-tools/quick-sharun.sh
              chmod +x quick-sharun
            fi

            rm -f "dist/${ARCH}.sha256sum.txt"

            for b in $utils; do
              if [ "$b" = 7z ]; then binpath="/usr/lib/7zip/7zz"; else binpath=$(which "$b" 2>/dev/null); fi
              if [ ! -x "$binpath" ]; then
                printf "%b%b\n\n 💀 ERROR: cannot create %b \n\n%b\033[0m\n" "$RED" "$DIVIDING_LINE" "$b" "$DIVIDING_LINE"
                continue
              fi

              ./quick-sharun --make-static-bin --dst-dir am-bins "$binpath"

              if [ "$b" = 7z ]; then mv ./am-bins/7zz ./am-bins/7z; fi

              cp ./am-bins/"$b" ./dist/"$b"-"${ARCH}"-static
              cp ./am-bins/"$b" ./dist/"$b"_static-"${ARCH}"

              sha256sum ./dist/"$b"-"${ARCH}"-static >> ./dist/"${ARCH}".sha256sum.txt
            done

            echo "✅ All binaries for ${ARCH} built successfully!"
          '

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: static-binaries-${{ matrix.arch }}
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          mkdir -p merged
          find artifacts -type f -name "*-static" -exec cp {} merged/ \;
          find artifacts -type f -name "*.sha256sum.txt" -exec cp {} merged/ \;

      - name: Continuous release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ matrix.arch }}
          automatic_release_tag: continuous-${{ matrix.arch }}
          prerelease: true
          draft: false
          files: |
            merged/*-${{ matrix.arch }}-static
            merged/${{ matrix.arch }}.sha256sum.txt
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get date for snapshot
        run: |
          SNAPSHOT_TAG="$(date --utc +'%Y%m%d')"
          echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"

      - name: Create snapshot
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ matrix.arch }}-${{ env.SNAPSHOT_TAG}}"
          tag_name: "${{ matrix.arch }}-${{ env.SNAPSHOT_TAG}}"
          prerelease: true
          draft: false
          generate_release_notes: false
          make_latest: false
          files: |
            merged/*-${{ matrix.arch }}-static
            merged/${{ matrix.arch }}.sha256sum.txt
