name: test dwarfs Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        wget -q "$(curl -Ls https://api.github.com/repos/mhx/dwarfs/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*linux.*x86_64.*xz$" | head -1)" &&
        tar fx ./dwarfs*xz &&
        sudo mv ./dwarfs*/bin/* /usr/bin/ &&
        sudo mv ./dwarfs*/sbin/* /usr/sbin/ &&
        sudo rsync -av ./dwarfs*/share/man* /usr/share/man/ || exit 1
        dwarfs -h
        dwarfs --help
