name: JuNest Stock Build
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  #schedule:
  #  - cron: "30 22 * * 0-6"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    container: archlinux
    name: archlinux
    
    steps:
      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2
      - name: Install system dependencies
        run: |
          pacman --noconfirm -Syu base-devel git make python3 which diffutils sudo --needed
      - name: build
        run: |
          mkdir -p /tmp/dist && cd /tmp/dist
          git clone https://github.com/fsquillace/junest.git
          ./junest/bin/junest build -n

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: junest-x86_64.tar.gz
          path: "/tmp/dist"
          retention-days: 7
        continue-on-error: true


  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: junest-x86_64.tar.gz

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous stock release
            automatic_release_tag: continuous-stock
            prerelease: true
            draft: false
            files: |
              junest-x86_64.tar.gz
            repo_token: ${{ secrets.GITHUB_TOKEN }}
