name: utils2appimage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # Set up Docker Buildx for cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Run your script inside the appropriate container with dependencies installed
      - name: Run script in container
        run: |
          IMAGE="ubuntu:22.04"
          if [ "${{ matrix.arch }}" == "aarch64" ]; then
            docker run --rm --platform linux/arm64 -v $PWD:/workspace -w /workspace $IMAGE bash -c "apt-get update; apt-get install -y python3 python3-pip make gcc wget curl xz-utils busybox p7zip-full file binutils; chmod +x ./utils2appimage.sh; ./utils2appimage.sh"
          else
            docker run --rm --platform linux/amd64 -v $PWD:/workspace -w /workspace $IMAGE bash -c "apt-get update; apt-get install -y python3 python3-pip make gcc wget curl xz-utils busybox p7zip-full file binutils; chmod +x ./utils2appimage.sh; ./utils2appimage.sh"

      # Upload artifacts for release
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: output-${{ matrix.arch }}
          path: ./output/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download x86_64 artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: output-x86_64
          path: ./release/x86_64

      - name: Download aarch64 artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: output-aarch64
          path: ./release/aarch64

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/x86_64/*AppImage*
            ./release/aarch64/*AppImage*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
